### ISSUE TITLE
(Test data) Adding a comment results in HTTP 500 from API due to validation

### ISSUE THREAD

**Issue by mglaman** [SoftwareEngineeringDaily/sedaily-front-end#617]
I was working on tests for comments for #607 when I hit this:

```
"Error: ForumThread validation failed: author: Path `author` is required.
    at APIError.ExtendableError (/app/dist/server/helpers/APIError.js:35:11)
    at new APIError (/app/dist/server/helpers/APIError.js:63:101)
    at /app/dist/config/express.js:120:20
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/express/lib/router/index.js:635:15
    at next (/app/node_modules/express/lib/router/index.js:260:14)
    at /app/node_modules/express/lib/router/index.js:635:15
    at next (/app/node_modules/express/lib/router/index.js:260:14)
    at next (/app/node_modules/express/lib/router/route.js:127:14)
    at /app/dist/server/controllers/comment.controller.js:269:22
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)"
```

**Comment by andrewmarklloyd** [comment]
I’ll look into this. It doesn’t happen in prod so I suspect it’s something with the way we seed the mongodb

**Comment by mglaman** [comment]
👍 Looks like it's in

```
        switch (entityType.toLowerCase()) {
          case 'forumthread':

            // TODO: move these so we also email for posts:
            // get entity outside of this function and then pass down:
            if (parentCommentId) {
              // TODO: don't email if you are the author and replying to own stuff:
              ForumNotifications.sendReplyNotificationEmail({
                content,
                threadId: entityId,
                userWhoReplied: user
              });
            }

            if (mentions) {
              ForumNotifications.sendMentionsNotificationEmail({
                parentCommentId,
                content,
                threadId: entityId,
                userWhoReplied: user,
                usersMentioned
              });
            }

            ForumNotifications.sendForumNotificationEmail({
              threadId: entityId,
              content,
              userWhoReplied: user
            });
            return ForumThread.increaseCommentCount(entityId).then(() =>
              res.status(201).json({ result: commentSaved }));
          default:
        }
```

Something in there errors

**Comment by andrewmarklloyd** [comment]
When we build the Mongo image we [exclude the users collection](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/master/devops/build-mongodb.sh#L10) so we don’t expose anyone’s data from the staging DB. What we could do is dump the userID but exclude all the other info.

**Comment by mglaman** [comment]
That feels kind of weird that this is happening when the comment is added for a registered user.

Or is the problem that the posts are exported and the author doesn't exist? I guess the problem is that I don't know where/why there is a required `author` property. 

Is it due to the following:

```
            return ForumThread.increaseCommentCount(entityId).then(() =>
              res.status(201).json({ result: commentSaved }));
```

http://localhost:4040/api/comments/forEntity/5d5774faec81b30038f32697

The forumThread entity `5d5774faec81b30038f32697` has some kind of malformed `author` ID and that's where it goes 💥 ?

**Comment by mglaman** [comment]
Ah yeah, okay. So the problem is the `forumThread.author` ObjectID is invalid.

@andrewmarklloyd what if the mongo script re-assigned all forumThread authors to the admin?

**Comment by andrewmarklloyd** [comment]
Awesome find @mglaman!

**Comment by andrewmarklloyd** [comment]
@mglaman the problem with re-assigning the forumThread authors to the admin is this would be a mongo query we would have to run on the staging DB. We can't edit the `forumthreads.json` that is outputted by `mongodump` (AFAIK).

**Comment by mglaman** [comment]
@andrewmarklloyd ah okay. Well, https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/618 works with a reload trick. Should I move forward there? I need to review the styling regression of the spinner pushing down the edit button.

**Comment by andrewmarklloyd** [comment]
@mglaman I might have a way to do it. Gonna test it out now

**Comment by mglaman** [comment]
🚀 this made it work, https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/618/commits/0553c088eff86e98bcdd20867f34f347483d9e57
